# Analise dos dados

In [1]:
import pandas as pd

In [2]:
cols = [
            "A1",
            "A2",
            "A3",
            "A4",
            "A5",
            "A6",
            "A7",
            "A8",
            "A9",
            "A10",
            "A11",
            "A12",
            "A13",
            "A14",
            "A15",
            "A16", ]
credit_file = "./credit/crx.data"
df = pd.read_csv(credit_file,names=cols, header=0)

In [3]:
df.head()

  A1     A2     A3 A4 A5 A6 A7    A8 A9 A10  A11 A12 A13    A14  A15 A16
0  a  58.67  4.460  u  g  q  h  3.04  t   t    6   f   g  00043  560   +
1  a  24.50  0.500  u  g  q  h  1.50  t   f    0   f   g  00280  824   +
2  b  27.83  1.540  u  g  w  v  3.75  t   t    5   t   g  00100    3   +
3  b  20.17  5.625  u  g  w  v  1.71  t   f    0   f   s  00120    0   +
4  b  32.08  4.000  u  g  m  v  2.50  t   f    0   t   g  00360    0   +

In [4]:
df.describe()

               A3          A8         A11            A15
count  689.000000  689.000000  689.000000     689.000000
mean     4.765631    2.224819    2.402032    1018.862119
std      4.978470    3.348739    4.866180    5213.743149
min      0.000000    0.000000    0.000000       0.000000
25%      1.000000    0.165000    0.000000       0.000000
50%      2.750000    1.000000    0.000000       5.000000
75%      7.250000    2.625000    3.000000     396.000000
max     28.000000   28.500000   67.000000  100000.000000

Como podemos ver, só o A3, A8 A11 e A15 são numericos, e o restante não é.
No entanto não é o que a base de dados nos diz.

"**A2**:	continuous.

**A3**:	continuous.

A4:	u, y, l, t.

A5:	g, p, gg.

A6:	c, d, cc, i, j, k, m, r, q, w, x, e, aa, ff.

A7:	v, h, bb, j, n, z, dd, ff, o.

**A8**:	continuous.

A9:	t, f.

A10:	t, f.

**A11**:	continuous.

A12:	t, f.

A13:	g, p, s.

**A14**:	continuous.

**A15**:	continuous.
"

## Vamos ver que tipo de dados tem o A2

In [5]:
df["A2"].dtypes

dtype('O')

como podemos ver é um object type e não é numérico

Teremos que converter para float64!

In [6]:
df['A2'].describe()

count     689
unique    349
top         ?
freq       12
Name: A2, dtype: object

Como podemos ver todos os NaN são representados com o **char '?'** (foi analisar a base de dados)

Então vamos converter todos os char '?' em NaN

In [7]:
df[df == '?'] = None

In [8]:
df['A2'][df['A2'].isna() == True]

82     None
85     None
91     None
96     None
253    None
285    None
328    None
444    None
449    None
499    None
514    None
607    None
Name: A2, dtype: object

In [9]:
len(df['A2'][df['A2'].isna() == True])

12

Existem 12 NaN no A2

Vamos então usar a func mean() para preencher os NaN

In [10]:
df['A2'] = pd.to_numeric(df['A2'], errors='coerce')
df['A2'] = df['A2'].fillna(df.A2.mean())

In [11]:
df.describe()

               A2          A3          A8         A11            A15
count  689.000000  689.000000  689.000000  689.000000     689.000000
mean    31.569261    4.765631    2.224819    2.402032    1018.862119
std     11.861851    4.978470    3.348739    4.866180    5213.743149
min     13.750000    0.000000    0.000000    0.000000       0.000000
25%     22.670000    1.000000    0.165000    0.000000       0.000000
50%     28.580000    2.750000    1.000000    0.000000       5.000000
75%     37.750000    7.250000    2.625000    3.000000     396.000000
max     80.250000   28.000000   28.500000   67.000000  100000.000000

Agora temos que fazer o mesmo para os restantes numéricos. Vou por uma lista com todos o valores que são numéricos que faltam e depois fazer exatamente o mesmo

Afinal depois de rever os dados só falta o A14. Vamos a isso!

In [12]:
df['A14'] = pd.to_numeric(df['A2'], errors='coerce')
df['A14'] = df['A14'].fillna(df.A2.mean())

In [13]:
df.describe()

,A2,A3,A8,A11,A14,A15
count,689.000000,689.000000,689.000000,689.000000,689.000000,689.000000
mean,31.569261,4.765631,2.224819,2.402032,31.569261,1018.862119
std,11.861851,4.978470,3.348739,4.866180,11.861851,5213.743149
min,13.750000,0.000000,0.000000,0.000000,13.750000,0.000000
25%,22.670000,1.000000,0.165000,0.000000,22.670000,0.000000
50%,28.580000,2.750000,1.000000,0.000000,28.580000,5.000000
75%,37.750000,7.250000,2.625000,3.000000,37.750000,396.000000
max,80.250000,28.000000,28.500000,67.000000,80.250000,100000.000000

como lidar com None nos dados catergoriais? Eu não sei por isso vamos eliminar!

Vamos primeiro analisar onde estão os null e pensar um bocado!

In [14]:
df.loc[pd.isnull(df['A1'])]

,A1,A2,A3,A4,A5,A6,A7,A8,A9,A10,A11,A12,A13,A14,A15,A16
247,None,24.50,12.750,u,g,c,bb,4.750,t,t,2,f,g,24.50,444,+
326,None,40.83,3.500,u,g,i,bb,0.500,f,f,0,f,s,40.83,0,-
345,None,32.25,1.500,u,g,c,v,0.250,f,f,0,t,g,32.25,122,-
373,None,28.17,0.585,u,g,aa,v,0.040,f,f,0,f,g,28.17,1004,-
452,None,29.75,0.665,u,g,w,v,0.250,f,f,0,t,g,29.75,0,-
478,None,26.50,2.710,y,p,None,None,0.085,f,f,0,f,s,26.50,0,-
488,None,45.33,1.000,u,g,q,v,0.125,f,f,0,t,g,45.33,0,-
519,None,20.42,7.500,u,g,k,v,1.500,t,t,1,f,g,20.42,234,+
597,None,20.08,0.125,u,g,q,v,1.000,f,t,1,f,g,20.08,768,+
600,None,42.25,1.750,y,p,None,None,0.000,f,f,0,t,g,42.25,1,-
640,None,33.17,2.250,y,p,cc,v,3.500,f,f,0,t,g,33.17,141,-
672,None,29.50,2.000,y,p,e,h,2.000,f,f,0,f,g,29.50,17,-

Já pensei e vou eliminar...

In [15]:
df.drop(df['A1'].loc[df['A1'].isna()].index, inplace=True)

In [16]:
cols = [4,5,6,7,9,10,12,13]
for col in cols:
    df.drop(df[f'A{col}'].loc[df[f'A{col}'].isna()].index, inplace=True)

Com isso podemos apagar todos os numeros que estão na lista

# Splitting data: descriptive & target features

In [17]:
descriptive = df.iloc[:,0:15].values
target = df.iloc[:,15].values

In [18]:
from sklearn.preprocessing import LabelEncoder

In [19]:
labelEncoder = LabelEncoder()
descriptive[:,0] = labelEncoder.fit_transform(descriptive[:,0])

Conforme está dito nas apresentações, aqui fizemos uma conversão de Categoria para Numérico

Agora vamos ver todos os que são Categorias e converter

In [20]:
for i, cols in enumerate(df.columns[:-1]):
    if df[cols].dtypes == 'object':
        descriptive[:,i] = labelEncoder.fit_transform(descriptive[:,i])

Todos os objetos foram convertidos para labelencoder

In [21]:
descriptive[:,0]

array([0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0,
       0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1,
       0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0,
       1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1,
       0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1,
       0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0,
       1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1,
       0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0,
       1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1,
       0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1,
       1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1,
       0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0,
       1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1,
       0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1,
       0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1,
       1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1,
       0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1,
       0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0,
       1, 1, 1, 1, 1, 1, 0, 0, 1, 1], dtype=object)

In [22]:
encoder = LabelEncoder()
target = encoder.fit_transform(target)

In [23]:
target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [24]:
encoder.inverse_transform(target)

array(['+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+',
       '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+',
       '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+',
       '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+',
       '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+',
       '+', '+', '+', '+', '-', '-', '-', '-', '-', '-', '-', '-', '-',
       '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-',
       '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-',
       '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '+',
       '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+',
       '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+',
       '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+',
       '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+',
       '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+',
       '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+',
       '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+',
       '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+',
       '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+',
       '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+',
       '+', '+', '+', '+', '-', '-', '-', '-', '-', '-', '-', '-', '-',
       '-', '-', '-', '-', '-', '+', '+', '-', '-', '-', '-', '-', '-',
       '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-',
       '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-',
       '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-',
       '-', '+', '+', '+', '+', '+', '+', '+', '-', '-', '-', '-', '-',
       '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-',
       '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-',
       '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-',
       '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-',
       '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-',
       '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-',
       '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-',
       '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-',
       '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-',
       '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-',
       '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-',
       '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '+', '+', '+',
       '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+',
       '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+',
       '+', '+', '+', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-',
       '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-',
       '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+',
       '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+',
       '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+',
       '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+',
       '-', '-', '-', '-', '+', '-', '-', '-', '-', '-', '-', '-', '-',
       '-', '-', '-', '-', '-', '-', '+', '-', '-', '-', '-', '-', '-',
       '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-',
       '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-',
       '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-',
       '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-',
       '-', '-', '-', '-', '-', '-', '-'], dtype=object)

# Train Test Split

In [30]:
from sklearn.model_selection import train_test_split

In [37]:
descriptive_train, descriptive_test, target_train, target_test = train_test_split(descriptive, target, test_size=0.5, random_state=0)

In [38]:
descriptive_train

array([[0, 24.33, 2.5, ..., 0, 24.33, 456],
       [1, 65.42, 11.0, ..., 0, 65.42, 0],
       [0, 16.33, 0.21, ..., 0, 16.33, 1],
       ...,
       [1, 22.67, 1.585, ..., 0, 22.67, 0],
       [1, 25.58, 0.335, ..., 0, 25.58, 0],
       [0, 65.17, 14.0, ..., 0, 65.17, 1400]], dtype=object)

## Data Standardization

In [41]:
from sklearn.preprocessing import StandardScaler

In [42]:
standard_scaler = StandardScaler()

In [43]:
descriptive_train[:,:] = standard_scaler.fit_transform(descriptive_train[:,:])
descriptive_test[:,:] = standard_scaler.fit_transform(descriptive_test[:,:])

In [44]:
descriptive_train

array([[-1.3650083747903758, -0.6420352833357559, -0.5079135742947734,
        ..., -0.31362502409358894, -0.6420352833357559,
        -0.13705659221525052],
       [0.7325962378462111, 2.781611064256619, 1.3145667084799537, ...,
        -0.31362502409358894, 2.781611064256619, -0.2536199744496808],
       [-1.3650083747903758, -1.3086006467024873, -0.9989112034187881,
        ..., -0.31362502409358894, -1.3086006467024873,
        -0.25336435299741233],
       ...,
       [0.7325962378462111, -0.7803475962343525, -0.7040982164993469,
        ..., -0.31362502409358894, -0.7803475962343525,
        -0.2536199744496808],
       [0.7325962378462111, -0.5378844453097041, -0.972110022789748, ...,
        -0.31362502409358894, -0.5378844453097041, -0.2536199744496808],
       [-1.3650083747903758, 2.7607808966514082, 1.9577950435769162, ...,
        -0.31362502409358894, 2.7607808966514082, 0.10425005872620172]],
      dtype=object)

# Naive Bayes Algorithm

In [46]:
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(descriptive_train, target_train)

GaussianNB()

In [48]:
prediction = classifier.predict(descriptive_test)

## Accuracy and Matrix

In [52]:
from sklearn.metrics import confusion_matrix, accuracy_score
accuracy = accuracy_score(target_test, prediction)
matrix = confusion_matrix(target_test, prediction)

In [53]:
accuracy

0.8

In [54]:
matrix

array([[101,  50],
       [ 17, 167]])